apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lmdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo # GKE SSD Storage Class
